# These config values will be shared by all environments but can be overridden.
common: &common
  client_id: "booking_sync_mailer"

development:
  <<: *common
  brokers:
    - 127.0.0.1:9092

test:
  <<: *common
  brokers:
    - 127.0.0.1:9092

production:
  <<: *common
  brokers:
    - kafka1.myapp.com:9092
    - kafka2.myapp.com:9092
    - kafka3.myapp.com:9092
